### ISSUE TITLE
All items are in alphabetical order

### ISSUE THREAD

**Issue by Ciante79** [artscout/Broker_portals#12]
Every items and every submenu items are all in alphabetical order instead of ID order like before

Would it be possbile to revert the change? (or make an option to toggle between the two?)

**Comment by artscout** [comment]
That I'm not sure is possible. Will check

**Comment by artscout** [comment]
Now this is what I found so far:
1. All of the mage/race/class spells were in  alphabetical order from the beginning. This is becase they were printed by different method (by using generatelinks and PairsByKeys and PairsByKeys using sort on table)
2. Other items were in order in which they were filled into the database because they were printed by simple iterating though lists.

So yeah, I've made this configurable )

**Comment by artscout** [comment]
And released
